use ExtUtils::MakeMaker;
#
# This Makefile.PL generated on Thu Dec 22 15:46:41 PST 2005 by nwiger
# running the magical "perlpkg" script.
#
# Eeek! I didn't star with h2xs. Oops.
#
WriteMakefile(
    NAME          => 'Config::Fast',
    VERSION_FROM  => 'lib/Config/Fast.pm',   # finds 
    PREREQ_PM     => {},            # e.g., Module::Name => 1.1
    ABSTRACT_FROM => 'lib/Config/Fast.pm',   # retrieve abstract from module
    AUTHOR        => 'Nate Wiger,IT/OG,44760 (nwiger)',      # author name
);
